optimizing script and getting rid of forced fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,25 +36,33 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Update only on changes in src/lambda/test
+        id: check-changes
         run: |
           if [ -n "$(git diff --name-only ${{ github.sha }}..$GITHUB_SHA | grep '^src/lambda/test')" ]; then
             echo "Changes detected in src/lambda/test. Proceeding with the workflow."
           else
             echo "No changes in src/lambda/test. Skipping the workflow."
-            exit 0
+            exit 1
           fi
       - name: Configure AWS Credentials
+        if: success() && steps.check-changes.outcome == 'success'
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-1
       - name: Create test zip file 
+        if: success() && steps.check-changes.outcome == 'success'
         run: |
           cd src/lambda/test
           zip -r test.zip .
       - name: Update test function
+        if: success() && steps.check-changes.outcome == 'success'
         run: |
           aws lambda update-function-code \
           --function-name test \
           --zip-file fileb://src/lambda/test/test.zip
+      - name: Clean up check-changes fail
+        if: steps.check-changes.outcome != 'success'
+        run: |
+          echo "Cleaning up failure in src/lambda/test job"
